github_token: ENC[AES256_GCM,data:TWTIdPih2Dhrhz0VqqJKpQL6IHSMWDnlgML/cOmkIoMZskjKJ1YyuQ==,iv:JsZIzi/q8qxJI0+ok0uvzz/MOercfhJ5vugdEgz/JX4=,tag:c6qUGvszM2A9f7U+X0+LbQ==,type:str]
sops:
    lastmodified: "2026-05-24T22:33:46Z"
    mac: ENC[AES256_GCM,data:Enj8M+xh1zNK8Xw1DoWCFQUlN5LA/TyDYl4+Kb4sxvEetoAyLH7+NFgfT2CVVQxahbPzTAtZKNBwYRFnbVPjvi72BMt0bSw3EwaioiEf4hl99vc361AnnMXnn02IOFm9WUoWV6RI5G1x8Of4NY8eAic7MTj8nHQQDuNIjqidc5A=,iv:2MmlIRUuTutr2t2XKN2wCdPHhaggWZ/n68wJz+xr0JM=,tag:0jGn7Sm3UvPYkIYQfo3nuw==,type:str]
    pgp:
        - created_at: "2026-05-24T22:33:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7Jgp6CDnvTzARAAtQgRmjWyOBoutwD1jnOTyaeB8RVc3uwbFhkjh+q/hc2/
            fa7LVY7dWlhbzmrtXxoxRJan4GjFnVqMGitSq4poPaFdg+fsSc9x2H9PC0h+zabX
            qgeuOUPPPgTvDRNE2CAu8jvTbnHzuyu9QRyrJ/dCGju8ztobi8ncIezpEsi3JM9r
            8VevFuKd6ZLZvtoSd5X8z3qUiJNSzDdlUvikjqJmcf2+Pse3yiLsf9cRT4KmSRuH
            SzEGJDnLcBO/inBAxVmpOyupgyjxh/Rnlu0nAeRNbCf3mVqe3TlOfGzTlVArZN/c
            ZUm5yQQlPlebQvh3Z7ah/478spB2cBBEmuc+PqztpPJqRZHAiTGnrJ3wfhhlcakC
            2rmlWng4BUq4IBZIyrFKloZRDazSxWgjlGdgZob7H2JOqeCiK6OF7YfD5NyNwrVY
            G0JHNzPSz1Kp3iUm4ZtkplFxOouc8/BOM9TCviu9B6wSkJEAbfG4Q8kRKJVOVmhs
            Hhq1sbuw1muUbdjQeiwNPapiX5tXiagc89ErbKLbvJdFD5Abm1k7iGEECr1JIlni
            jQlZp9Fan+9S1AjFAwBaLS6IxYLNn6LXi1O7Q5oCxYo/IhmsnnlN6Gu385zjiQyj
            jXFuD9dlrGlLSSVtP4pF8Vya8KhrNsCh+pVlnxb/AihM9hCmiY8HRiZX0MH8OMzS
            UQEMwygKMnXZgaBYyisAa/YlSwbzNGwW54V1375hCvGU3aeWM9F/u3+AlxeysCn0
            6Ho4H6bR9Cke5NCdyIiwai3fZ4GiRtu1p0wE/kbOn/Kr3Q==
            =mfCY
            -----END PGP MESSAGE-----
          fp: C3BBA44AF96094B68AB3758AC89FF184D4033338
    unencrypted_suffix: _unencrypted
    version: 3.13.1
