github-token: ENC[AES256_GCM,data:V78q0P9g+0tipA/p5vj8jhM/k7GdtB3BHnWLzHCuBIbmv1UgUv7b4A==,iv:rHKkaQbe7FX4Tgo8IS122qdsvlYoKBo0djHESMWagq8=,tag:yqHh8ZalROUIPVV0ekt7Kw==,type:str]
sops:
    lastmodified: "2026-05-24T22:04:44Z"
    mac: ENC[AES256_GCM,data:pPNy6LaLQCNpOSLyZCMW7qzqmT1zgDcKcJHKXjHK9PLjUQ9Tlo+bHnsgqCTMAIvWYVJAU6n7BCzhFhQcnHAVYcWyFnJq9ubyOrk755mXAdd19AoOs24O66ESjTTMfYi54KMysyh70T+SooEIMTw7eUUGPNtCjzY94uXOwSnKnV0=,iv:VdBtdNIaT0pVX/e+rK53LxS0dFmdluXX0sk5AijIKa8=,tag:MV88zIVlL5fovATUa3BjyQ==,type:str]
    pgp:
        - created_at: "2026-05-24T22:04:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7Jgp6CDnvTzARAAi/2HuHEM677vYhK4JB82C0+dTukKhDdwmv6TEHYCEG3t
            kb/O5y0bte3xfxC/NqZqEfPFvyG/lAIFT9UqTkh80mnoOdWTJtoloYtxeg9JHTzO
            QIHpCy9sF/tkKgiQ8He09GVHF7pmJ6A6X6RzNEjumKa+YPTg+/NySyx4FI1c83om
            Xi/0mLbt7y/d4/IP9rCXWO+1DfRmbNG0iSk3beSPjF9RfRVl1k7EVa8fkU+7str0
            J1wOadx4ltwL45oTCYMgEmhhFhj0JpwLphLoiN1tuQkJXuY0EDobHO9qA1cCKHTf
            EhB+5ppH16NsQcqX5Jn0Z5lcoKT/klB4I0Kx1TV20feDiUQ2R6RjXxsADTu18to3
            2Pm/ocZCR6oSlqaceLAvdTRPjaowvfBL/BQrKmR96J+2xmWImu4X2Yo42tkhwXyT
            M+J/xSNElnVHyxj7pgFx4hC1EeBv+EroNEY4z6VPjK4CoHP4YmZMkDGhHx6pYU2r
            vtEbQYxhN3q5lSn4DiWMnB3WOuuSgI5tVRhRlmwK6ojhWa3jot/DK4GbtI5FCpHV
            FZ0p2ZAjxT7sHlW7BIZ1p5FH5cOQJreE2T1FNjPMLh+npMuhLB8pqOmTomb5L/6M
            S9bRkzANYUImFH0H+h839D4dzI9rFXFKMCujFywes3NvzlOsDHaKGBJFan6+aWfS
            UQE+WsWu5z5zTWt8RnNbjlL1RvAQWGljscyFspl2UvxFRWfdkUZh4ZkWVRI1yC3R
            68rcU4Bjw0ong0G3RtkQoZfumqGKzwCyPSPBjW4VrOD3iA==
            =SrzS
            -----END PGP MESSAGE-----
          fp: C3BBA44AF96094B68AB3758AC89FF184D4033338
    unencrypted_suffix: _unencrypted
    version: 3.13.1
