githubConfigUrl: https://github.com/gabriel-suela/homeops

githubConfigSecret:
  github_token: ref+sops://secrets.enc.yaml

runnerScaleSetName: kind-runners

minRunners: 1
maxRunners: 5

containerMode:
  type: dind
controllerServiceAccount:
  namespace: arc-system
  name: arc-gha-rs-controller

template:
  spec:
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
