githubConfigUrl: https://github.com/gabriel-suela/homeops

githubConfigSecret:
  github_token: ref+sops://secrets.enc.yaml#github_token

runnerScaleSetName: kind-runners

minRunners: 1
maxRunners: 5

containerMode:
  type: kubernetes
controllerServiceAccount:
  namespace: arc-system
  name: arc-gha-rs-controller

template:
  spec:
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
    volumes:
      - name: work
        ephemeral:
          volumeClaimTemplate:
            spec:
              storageClassName: standard
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 1Gi
