name: pre-commit

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: actions/setup-python@v3
        name: Install dependencies

      - name: Run pre-commit
        run: pre-commit run --all-files
